version: '3.8'

services:

  postgres_db:
    image: postgres

    container_name: postgre_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password

  #DATOS DE ACCESO A PGADMIN
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 6080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

    depends_on:
      - postgres_db

  app:
    build:
      context: ./
    ports:
      - 5000:5000 #El guion (-) indica que estamos creando un array.
    depends_on:
      - postgres_db
    volumes:
      - ./src:/app/src
